--[[
    Entries here trigger when you or a party/alliance member(if enabled) cast a spell that states the debuff on a monster.
    This is intended for spells that explicitly state the debuff, such as 'Player casts paralyze.  Mob is paralyzed.'.
    Status effects can be listed by ID or by name.  If both are present, ID takes priority.
]]--

return {
    [5] = "Blinded.wav",
    [6] = "Silenced.wav",
    [7] = "Petrified.wav",
    [8] = "Diseased.wav",
    [10] = "Stunned.wav",
    [11] = "Bound.wav",
    [15] = "Doomed.wav",
    [16] = "Amnesiad.wav",
    [21] = "Addled.wav",
    [22] = "Intimidated.wav",
    [28] = "Terrored.wav",
    [31] = "Plagued.wav",
    [128] = "Burned.wav",
    [129] = "Frosted.wav",
    [130] = "Choked.wav",
    [131] = "Rasped.wav",
    [132] = "Shocked.wav",
    [133] = "Drowned.wav",
    [136] = "Strength Downed.wav",
    [137] = "Dexterity Downed.wav",
    [138] = "Agility Downed.wav",
    [139] = "Vitality Downed.wav",
    [140] = "Intelligence Downed.wav",
    [141] = "Mind Downed.wav",
    [142] = "Charisma Downed.wav",
    --[156] = "Flashed.wav",
    [192] = "Requiemed.wav",
    [194] = "Elegyed.wav",
    [217] = "Threnodyed.wav",
    [223] = "Nocturned.wav",
    [597] = "Inundated.wav",
    [2] = "Slept.wav",
    [19] = "Slept.wav",
    [3] = "Poisoned.wav",
    [4] = "Paralyzed.wav",
    [9] = "Cursed.wav",
    [20] = "Cursed.wav",
    [12] = "Gravitied.wav",
    [567] = "Gravitied.wav",
    [13] = "Slowed.wav",
    [14] = "Charmed.wav",
    [17] = "Charmed.wav",
    [146] = "Accuracy Downed.wav",
    [147] = "Attack Downed.wav",
    [148] = "Distracted.wav",
    [149] = "Defense Downed.wav",
    [167] = "Magic Defense Downed.wav",
    [174] = "Magic Accuracy Downed.wav",
    [175] = "Magic Attack Downed.wav",
    [404] = "Frazzled.wav",

    --Geomancy..
    [540] = "Poisoned.wav",
    [557] = "Attack Downed.wav",
    [558] = "Defense Downed.wav",
    [559] = "Magic Attack Downed.wav",
    [560] = "Magic Defense Downed.wav",
    [561] = "Accuracy Downed.wav",
    [562] = "Distracted.wav",
    [563] = "Magic Accuracy Downed.wav",
    [564] = "Frazzled.wav",
    [565] = "Slowed.wav",
    [566] = "Paralyzed.wav",
};